apiVersion: v2
name: Database
description: A Helm chart for Kubernetes to deploy PostgreSQL

type: application

version: 0.1.0
appVersion: "17"

dependencies:
  - name: postgresql
    version: "18.8.0"
    repository: "https://charts.bitnami.com/bitnami"