ingress-nginx:
  controller:

    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet

    service:
      enabled: false

    ingressClassResource:
      name: nginx
      enabled: true
      default: true

    admissionWebhooks:
      enabled: true

      createSecretJob:
        enabled: true

      patch:
        enabled: true
        enabledByDefault: true

    config:
      use-forwarded-headers: "true"

    replicaCount: 1

    containerPort:
      http: 80
      https: 443