minio:
  mode: standalone
  auth:
    existingSecret: minio

  persistence:
    enabled: true
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 10Gi
    existingClaim: ""

  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m

  buckets:
    - name: mini-kafka
      policy: none        
      purge: false        
      versioning: false
  environment:
    MINIO_API_CORS_ALLOW_ORIGIN: "http://app.kafka.ophkmh.com:8080,http://app.kafka.ophkmh.com"