apiVersion: v2
name: helm-init-chart
version: 1.0.0
appVersion: 1.23.0
description: A sealed-secrets chart wrapper for cluster intialization

dependencies:
  - name: sealed-secrets
    version: "2.5.19"
    repository: "https://charts.bitnami.com/bitnami"