---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio
  namespace: minio
spec:
  encryptedData:
    root-password: AgA1s1R7jGVlOcnvAP1lMxswJzwYRpnd+1S4aIU9j+MiZp1si++x25FRtlj4TG8LtoLoFqlSlfUt5Jpzca9/DwVCpyjHoSy/Hwwutr6vleL63OVHB4JTBAEVOyWkfVKGUxAx+omG2nfmhIdZA724BhvaFJq/Bcgbg0Wduo+5DC/vT4knyFNnWc9b/iDBWXGWSPwkJyUTR634rUPKp/pRHDpFZjQ4iwKMbCKT+IuGyuwiqFo5etx/Fl2wfnv6RTYdDXgm7Pi7cXc+GmQeFIQvmajFwBm1Fxdk34fGUpvzwKb4F+ftKlg33kjBWGeNGw/hhwNkLuNb0Cuf6VuVCM8e/zMeGGXf/zXi2vGhQlBq2JMineqgA89o1h+M/ZBZNEr5rbSqn2iw2SiRqKvxt+LB+5l11DAh8ssy58xI7CdykH1WPs1ODjVn+mOj56qmFhFRkgYuXLe3urgTnNwuPXY99Iw9yNxFifsxOoaYWWNK7MeNM28HdRcUKmO67FCLnq17mNkJ//yr8I+0j31MOAAvyoeoRlzBoer5gUMfH1LhHBWJ+OmOsRAs8FhGWxcAp82bqriKfga262jN/EyQt13QDKLZ4wOYWylND69t7in0K67T9Nros5GUM7OQJDJ/PlI3GBlzfe9qmrBCnVyodKN7nx7IbsyTxh/7krUXStNhrwDRhipZgy6V+xUlOE5NhervjuSMNLcHSyxji9q7P8TUFx6sPwxuP2dVBjc=
    root-user: AgC+hch4MFw/c6MxAB+SQgyhyrhtj7o/rAIL8nwJ/1sTOCueLksgvUq3KkoTuWd8nVwf1HcDl3T9CtOFIXmwC3EXNanvFarwllj90gqxDhwT9C1SkCMhA3bHADIVUBh8QAjjXhZdHtz/mHEmnnljaxkvEPaL8B90Pla/XeP4ZE+NCbj15YD5EWEL8Jl6oyyhr5tyrLY5W09Z218STHs1hwuZLS//aLVokt3HGAatHr3tOQY2cT28KnNNJ1W+bNKS2ga+Km6JLgjTt2+REQABL57Xhv8vXG4nJHHg9qzfPQPU6IWFb6u5KrBGP8Pk+21gzw8DJPnDtAPq2EQtFxeqZNIE9FUnyCnZ8m7/3ExHBmW6YmXx7SpBAIOBQmsHe7MaHi32BNMo1UOC7d7X2AmYbtUpxSUg34btC1QcafsfYEITOTnbTCX1z6H9jfdgWkmv8LxVkv0E4syw9TNgKMSxG2kijP1cH+psnqbUrjYmCOkSE/1NJc3x55lt2GJyk/mFohLgGWnD9/dKvRq4AFYIzVlvZuYD2I2TAHsSm36hWicWCj0+jZz2q87q3kCd0fnFju807jHLkFj9gOPHRn9RqUuksaLf9lcuvdyI3f3CiOfHqsk+lNTC21atEDSvPd/1IoJt17oeQixxim7g7f0kCdjhwWunMG9RAnQxQyEp6mXSf4z+ep9JpV8T21jGMla3SGk4kAf/qkvqzRr5HfjnJT7cywIDKNj1cVo=
  template:
    metadata:
      creationTimestamp: null
      name: minio
      namespace: minio
