---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgC4VssKxWTxyVlWVK7Qoksiug52Qjd17DoUDAV8UQZb2VR7+vwQX/G6nGQbBWz2bpkaPgYG66qbgGz/sHcUXgVBdhoyqtdlvon0yNn6GJKqcalqIUV91hEgiDHrQsHC+Xkz0lwCPWpimEpHcNSA88j/cbastYRWFHEVCsaT2+wfCBICh0zdtsnHc0vxTNvQyQQ0lO54pgw6esXLWtmwJdPhY3iZiwNNLxPJCyIWKuhypKXQLEZ1elTIdEHW+pcMrz73GIpv3GiuCc7K4ezl+wg2gf6OwfX2YEwbB0xdH5PfRdVWONJQvVKtkQbqBcMQ4bzGTRPJH5isZGsql8fKYmyYD+jJapJhKzYUxBSUXNF/kogufgwwTypJi1EBlzVbeAPIp1Njbm6hs9Jc2L55iviu7Krmpj+iQFUYq+dDZVsqo/dMwejiuVg6FNeDsV0V6/x7Xf/RSJZt1IcnoS/QwaNvFK5JLJlZ9hWKfhMjglvXKY/nXMVMT7ARcVZ6pMtHT3aRsv9zQ1kTM+AvAgWa2PofyDgnCyYOxmbQ1Mo0v6lIfLBfLpXgWQyU+PgL2IoeGY75FEiQfVPg6aXLaEJlLVed3t8lCWfMwqQZHmOrZihcmBWK/SpYgIihl1pI9aVybhnOqRBdpz+aZrLfhGaVUeqjvKuY4/0SVDhCoW4bvpZpag7BIFzrhUBqyF63txD2z6XTyZaQdXgghz95xvGaI2Aikum4meJ3czQ=
    rootUser: AgDa8Vgac5h/nVRkITfYGTDZepvpDEvMzHX1HbwO4WsHHsjdKS5g1mGr6XP8Ur62PP0UOHEVJmqtTXHWUpPgaKE4xKL8s6dy6RK3XCD+cepTKKIf0EEWF3tDs/8A+u8qve5GIcSTC4GmX5bXwoe9j6ANsZz/7bvP+5Kb7f3sHqKacTho4/68EB5PO0ubnhl4ZaLqVM4J8IS3qeD3K/rcf/gud2czsKfe1iDLCQKz6L56qachO53aTlVMwJgrBihKpy3SGen6b02ErqaGtfU8AC68nORr1HRowZvFVePM0VPRaQU8WlJbGoyLP1pN+SXQYY1dN+4NKzA9JBmNyi+bMEz9M4lXne77sxwFPm6EfpeE5WoAycHuEkdCBThJVfOKZ/+4ngQClR0cncmukUoVZRjfO0Ui+OOoo8t7B+TnHlyst5/GUW2cvr2zyQ4V8nCVoTmy5io1lUz04a/Ndsm3zHEB3dr53IgmOtnDZEnk7/0cGW/m5HABi+IldpAUVZYko6CkPTUK596Vct9B16on34muA9wYhKHiDdri3zH8d67eBmmHNOwgWteUy++xHwsxQZKkmp0STZuKHgHGYYPJwJ0U2wSEOW4HpaD+fRJNOIw8Mrl02e+ANyaNdvm0YFKbzOfTRsXIqp4NyudRF5sQIlumEwVP4R5+bGbmH8KPMMGI/hWzn9HCEMrEY6uk3UWhj0yA6+rXn9Xk2/2wHEg47pMrRa8I+xUJ7Lk=
  template:
    metadata:
      creationTimestamp: null
      name: minio
      namespace: minio
