---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-sealed
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgBke+vkl1oPEAktIDxUYFPlxRiiW3UyDMwOlTvqj1i8LN/CPVGUYFYSVhF8xwvKCtxt4HNBUBsvYHPnqakIgLzxBO3ze41WJAaGYEgqH7qG1mrbkdRvvrpdGPPtJGV7CRZRU4PdC3yqL33xR4ZQeYD157fMkPDcA2E0oxSuH+cnFCkPs1Mch+wvSeFYKucRWM/cgYt+97SUijPYKsONVc0l6Z/XDQsCvmyhl6oRqBQdhma98rPp8b6TqFTCpi9obUxts4F+2R0EMfBe9UCxwdZr1VdDLXpqj2X96feyDKDLdwuyY/KZEljz8tym9UZVSf7DlWmBL1enBBGNHwDnUnyMN87iims6BMF/KXnNU0/I2MYEwS75IEXn78Bx8QHZfaXb7QM/HiNP1F/7LDl1R9lyDAbHM7tv1IKTRkGxCoQy9+d/tNADkDnOvuPHlcLG/3EVoqeDuVBGJeBoS8WPRJ28TOwOg1nKd/TwEN1+Zbw40gSNbZ8AZ+L8u0e7CvdlatZVjsFGvpBnKizigE1SNkqC/PAlB/ggF2DlvZjAbwAgzo6MyeUi+buqBs5+VISE3CAJnYZ4W1XCRAAObh+gPiYz+Fy1G040MTDyosJCpzwWMvkOKOM0BipDThBoNASxCQP/fvZxYla50BoXsYd1Rmfe+z6tXt0koPKeJUidsXCEHbnqBr0YQHp1dOex2Utxf4BGin0Qj8FzXQyjvCXEqdfJJCtfrwjgc+w=
    rootUser: AgDcQpr5aI4Vzlt4VhxSjAQd+P222JHbn8IJmag9iqwlw05oSByDxg8vJhX0OHu4SiamRV0FeW8sWIBHweK+f9awHDT6aC62PKAiXhpVYZ8uz8PeZAfxPqRRYrgvwGr+BrYf9R3H9X4kMidpKKVeT5Y6Evh/iOdl2uGObqNGnM7dAEVTQgprJQsAzFN8KIDS4+xmlpMbZfnQRVx9s5Z8OmCBmSh8mwZN1vmxESEVelyMZO1TTuoYySM6G+H0qddDszVLDQN9BFi2hkcHBatxY3TCdSbeMgmuzQPHe9UV+UVo7j1xsu7nAjPi26HScRuZ8rsN3vpM7MT5vW1TULA61OsRwqmJCrQLbUqnpXCcsw4fniCR64XB+PYe9gFTHm9x4jfFju9Y0BXu4bIdGKI+0jQUSHN8pvIcx0ASivKnN8MA5lrG5/Q4dMMOndeP5QIeUfD8d8unpCY8oRh2mOXGlebejWSQ8Upr1hP1Y/mdFKNDFwoVrGzC7ibNTs1CVb6R7VvP5PJBgzjkC0Ux07sz5xYA67SvrkLYiaFvDx/zQLQD0bFVUY+m77wV3NeD2jF/I7WvQolV6TDU9UE3S7goi3cbpW/Zh3l3Q5QDLcAiluOjyKcDZryynXdLblzVeCdesZhqwapx6W3YuxzGZz3flKe6aaj9gq5IVjYzrG8cIaAoGxwCAU9zomxbUXX2sY/sFHbt2ENIS7nbWRz420kdTAsymcs4+iKQlhk=
  template:
    metadata:
      creationTimestamp: null
      name: minio-sealed
      namespace: minio
