---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-postgresql
  namespace: database
spec:
  encryptedData:
    postgres-password: AgDRBZ1K7mMN+ZyonvBsgHZeVYMpaP85qOig9XeqlhcZw8bMDLfPfe3w4/Y3P0SfIzJOKXlVszFnPTpqB8Bap4jb8EKQvMdfJP9qrONLT/73BVXqSanjNcidj0kp+EORc4PMIBvSGQW+CWdKHsJaBkD8BLGgdKNlUuRIJSFzi4l9fmt3HglJ4vraklMsAfl/gXRHwX8R/JRh4q/SzJW9oFSp01Ed+BkZzQY5/dgP6Ge5cs/+MY8u4dMIMnTWAtA+z2MYRZdc37yTjzUKw84CW3CuYr4dV2r/tDXE9jjgFotVe1q10OguXxOsHg5af12gM93+KZylwHWLg9LWmo3Hyk3Ea1RLqGkuy2aFgeQb9skEmZ4EAS7jb5H9rfZol87zfVIrJwPL3PDppwwrYRzlcjs8Y5gR7hd/Q7Qm4s655KlTBnMmZFPTtl/9JNdjvKe2D0SfjjuPucHfXfNxLvPcN0Mj2So2IuFFR5mmq0+TzEy2mV0Nadb3JW3NdllK3gj229Oxvt7rVZR1wdwPOzZijltqGHgipnpgvhcTnJ58ElpU716lf+0+ac7U2nK2sG9+flS3Acyu3aUpQh1SQvk6fHr3FM6jDpaan1ddg6ycsM9GZZeoYggGZCvcGzG6Y/Ugq+NdY5gPk9vEwQbXVUzAjDdihjZ6E5pJni6NMun9Hpw//Aj5mgcIbh2JPieYTH27CUl3kY/BBGnU1kUo/QVX6UGVaZcLbr6msXU=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-postgresql
      namespace: database
