---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-postgresql
  namespace: database
spec:
  encryptedData:
    postgres-password: AgBku7RZ2SwuXYwKR818LDfFK+pwtmh88JZJWiSpNYpfsENM4g4NOhJs1PqG0aTXKfbtNBTR1Ye+WY3fkTIY+7NLG2Zi6bECFvi2FWRbpmvCqv8nhxH1iH/Xv0Uj6CuQN3ARV7w5RsQAjWXX6bO7vEakLWMkm7L7OH+t38TyP8ZI9kao88MbSAErEzA4OeUmdTng4xNaw4sDkP6nJ7xH4AM/ox9jgp1IIz5sfEwKY2oA6bhzq7UzJ97sslEag4Rsvj3yIypwQA/t3zcoJJzR6JIMm46nQyq5TQJCxG/KdO8oFY58qt6j2v9g+dBKvxUK1whwgxEjg9zk8B3ADjTPLJ29srAYSu7LNK6fA+q0MmBWeZVStknbMl8W//JYzhJivbMPXtJ0GnzoEWdX8wCdUnr4lBaNt0/Hf4P4D6pfp7c1DySerpwxYBzdVqMSuNi/1LfcXYV9JKKIRkKxxrjLWJglKoC4mpdufrRwJXvPs1bFWF4GZLnruqBeD0sY4X1RsNGeZgT8niXIZWZlYNvjLUpYagQk73f/0mgnJQGglfDikTMZrJD02DfnyDHxA26LLGX9BU0d04Ssaj4erNXv9RC1kWT27itpdEh/e77WXwDtFfBcKBvJkurhfO4mkjVIzcucMWvA+m3uiYCerYE/9y7kXTnZLiHdFnJNl5Nlaer1XB0W1eXjqxmGBZbhuYTQcjm0EhPKfhgzUJSE3viM/2lRm5Ze8JJWVGY=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-postgresql
      namespace: database
