apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: postgres
  namespace: argocd

  annotations:
    argocd.argoproj.io/sync-wave: "-2"

spec:
  project: default

  source:
    repoURL: https://github.com/ohm-pkh/kafka-mini-project-argocd.git
    targetRevision: main
    path: applications/infrastructure/database

  destination:
    server: https://kubernetes.default.svc
    namespace: database

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true