apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: ingress
  namespace: argocd

  annotations:
    argocd.argoproj.io/sync-wave: "-1"

spec:
  project: default

  source:
    repoURL: https://github.com/ohm-pkh/kafka-mini-project-argocd.git
    targetRevision: main
    path: applications/infrastructure/ingress

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle