apiVersion: v2
name: kafka-ui
description: A Helm chart for Kubernetes to deploy kafka-ui

type: application

version: 0.1.0
appVersion: "17"

dependencies:
  - name: kafka-ui
    version: "1.6.4"
    repository: "https://ui.charts.kafbat.io/"