apiVersion: v1
kind: ServiceAccount
metadata:
  name: reflector-annotator
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reflector-annotator-role
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: reflector-annotator-binding
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
subjects:
  - kind: ServiceAccount
    name: reflector-annotator
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: reflector-annotator-role
  apiGroup: rbac.authorization.k8s.io